CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UserPoolName: SamSequelizeCrudUserPool-${self:provider.stage}
      UserNameAttributes: 
        - email
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: SamSequelizeCrudUserPoolClient-${self:provider.stage}
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - email 
        - profile
        - openid
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - implicit
      CallbackURLS:
        - https://jjlqnydai6.execute-api.us-west-2.amazonaws.com/dev
      DefaultRedirectURI: https://jjlqnydai6.execute-api.us-west-2.amazonaws.com/dev

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: SamSequelizeCrudUserPoolDomain-${self:provider.stage}
      UserPoolId: !Ref CognitoUserPool
      